import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LeftSidebar from "@/components/sidebar/LeftSidebar";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Nexsphere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-primaryBg text-primaryText`}
      >
        <div className="flex min-h-screen justify-center w-full">
          {/* Wrapper to control width dynamically */}
          <div className="w-full md:w-[85%] flex justify-between">
            {/* Left Sidebar (Hidden on small screens) */}
              <LeftSidebar />

            {/* Page Content (Full width on small screens, adjusts on larger screens) */}
            <main className="w-full min-h-screen transition-all duration-200 md:ml-[250px]">
              {children}
            </main>
          </div>
        </div>

        {/* 🔹 Modal Portal Div */}
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
