// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// // import SidebarWrapper from "@/components/sidebar/SidebarWrapper";

// export const metadata: Metadata = {
//   title: "Nexsphere",
//   description: "Generated by create next app",
// };

// const inter = Inter({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">

//       <body className={`${inter.className} antialiased bg-primaryBg text-primaryText`}>
//         {/* Sidebar Wrapper handles client logic */}
//         {/* <SidebarWrapper /> */}

//         <main>{children}</main>
//       </body>
//     </html>
//   );
// }

"use client";

import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ThemeProvider } from "@/context/ThemeContext";
import "./globals.css";

const queryClient = new QueryClient();

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <ThemeProvider>
            <TooltipProvider>
              <Toaster />
              <Sonner />
              {children}
            </TooltipProvider>
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
